- hosts: trainGui
  vars:
    - NODE_VERSION: v0.10.26
    - NODE_LOCAL_MODULES_PATH: "/usr/local/nodejs/node-{{ NODE_VERSION }}/lib/node_modules"
  roles:
    - nodejs
  tasks:
    - name: Download WiringPi from repo
      git: repo=http://github.com/robjcaskey/trainCap-wiringpi.git
           dest=/usr/local/src/trainCap-wiringPi
    - name: Install WiringPi from local src
      command: /usr/local/src/trainCap-wiringPi/build install
      args:
        chdir: /usr/local/src/trainCap-wiringPi
    - name: "Install dccpi from repo"
      pip: name=https://github.com/robjcaskey/dccpi/archive/master.zip
    - name: Install "socket.io" node.js package globally
      npm: name="socket.io" global=yes
    - name: Install "bower" node.js package globally
      npm: name="bower" global=yes
    - name: Install forever (to run Node.js apps) globally
      npm: name="forever" global=yes
    - name: Install trainCap-pinstripe
      npm: name="robjcaskey/trainCap-pinstripe" global=yes
    - name: "Update trainCap-pinstripes bower dependencies"
      command: "{{ NODE_LOCAL_MODULES_PATH }}/bower/bin/bower install --allow-root --config.interactive=false"
      args:
        chdir: "{{ NODE_LOCAL_MODULES_PATH }}/trainCap-pinstripe"
      changed_when: false
    - name: "copy trainCap-pinstripe init.d script"
      template: src=init.d/trainCap-pinstripe dest=/etc/init.d/trainCap-pinstripe mode=0751
    - name: "Restart trainCap-pinstripe"
      service: name=trainCap-pinstripe state=restarted
    - name: Install trainCap-brim
      npm: name="robjcaskey/trainCap-brim" global=yes
    - name: "Update trainCap-brims bower dependencies"
      command: "{{ NODE_LOCAL_MODULES_PATH }}/bower/bin/bower install --allow-root --config.interactive=false"
      args:
        chdir: "{{ NODE_LOCAL_MODULES_PATH }}/trainCap-brim"
      changed_when: false
    - name: "copy trainCap-brim init.d script"
      template: src=init.d/trainCap-brim dest=/etc/init.d/trainCap-brim mode=0751
    - name: "Restart trainCap-brim"
      service: name=trainCap-brim state=restarted
